name: Deploy to Netlify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Netlify
        run: |
          curl -H "Authorization: Bearer ${{ secrets.Or-VSEUAiUBbScShyvRRz1cNuAmwP-E7a6K6K-E7ou0 }}" \
          -X POST -F file=@./index.html \
          https://api.netlify.com/api/v1/sites/60030752-132a-4d76-a04d-d5e71fc87e71/deploys

      - name: Print Deployed URL
        run: |
          echo "Your website is live at: https://uniqueportpolio.netlify.app"

      - name: Update Commit Status with URL
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha,
              state: "success",
              description: "Website successfully deployed!",
              context: "Netlify Deployment",
              target_url: "https://uniqueportpolio.netlify.app"
            });
      - name: Post Comment with Deployed URL
        uses: actions/github-script@v6
        with:
          script: |
            const { context, github } = require("@actions/github");
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request
                ? context.payload.pull_request.number
                : context.sha,
              body: `✅ Your website is live at: [https://uniqueportpolio.netlify.app](https://uniqueportpolio.netlify.app)`
            });
      
                  
